# Generated by Django 3.1.2 on 2020-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ytvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yname', models.CharField(max_length=200)),
                ('ydesc', models.TextField()),
                ('ylink', models.TextField()),
            ],
        ),
    ]
